version: '3.8'
services:

  mysql:
    image: mysql:8.0.13
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1914"
      MYSQL_DATABASE_NAME: 'wordpress'
    ports:
     - 33306:3306
          
    volumes:
     - ./db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "1914"
      WORDPRESS_DB_NAME: 'wordpress'

    volumes:
     - ./wordpress_data:/var/www/html

    links:
     - mysql:mysql     

volumes:
  db_data: {}
  wordpress_data: {}

